"use client";

import { useEffect, useMemo, useState } from "react";
import { eloRatings, normalizeTeamName, prediction, simulation, teams, type Fixture, type HistoricalTeamStats, type Match, type PlayerFormData, type ScenarioOverride } from "../lib/analytics";

const pct = (value: number) => `${(value * 100).toFixed(1)}%`;
type SquadPlayer = PlayerFormData & { id: number; name: string; position?: string | null };
const playerScore = (player: SquadPlayer) => Math.round(Math.max(35, Math.min(99, 55 + player.recentStarts * 6 + player.recentBench * 2 + (player.seasonGoals + player.seasonAssists) * 2 + Math.min(9, Math.log10((player.marketValue ?? 0) / 1000000 + 1) * 3))));

export default function Home() {
  const [home, setHome] = useState("Tottenham");
  const [away, setAway] = useState("Arsenal");
  const [scenario, setScenario] = useState<Record<string, "AUTO" | "WIN" | "DRAW" | "LOSS">>({});
  const [live, setLive] = useState<{ standings: { position: number; team: string; played: number; points: number; goalDifference: number }[]; matches: { id: number; date: string; status: string; home: string; away: string; homeGoals: number | null; awayGoals: number | null }[]; updatedAt: string } | null>(null);
  const [liveError, setLiveError] = useState<string | null>(null);
  const [historical, setHistorical] = useState<HistoricalTeamStats[]>([]);
  const [players, setPlayers] = useState<SquadPlayer[]>([]);
  const [selectedLineups, setSelectedLineups] = useState<Record<string, number[]>>({});
  const [isRefreshing, setIsRefreshing] = useState(false);
  const liveResults = useMemo<Match[] | undefined>(() => { const completed = live?.matches.filter(m => m.status === "FINISHED" && m.homeGoals !== null && m.awayGoals !== null) ?? []; return completed.length ? completed.map(m => ({ home: normalizeTeamName(m.home), away: normalizeTeamName(m.away), homeGoals: m.homeGoals as number, awayGoals: m.awayGoals as number })) : undefined; }, [live]);
  const liveFixtures = useMemo<Fixture[] | undefined>(() => { const scheduled = live?.matches.filter(m => m.status === "SCHEDULED" || m.status === "TIMED") ?? []; return scheduled.length ? scheduled.map(m => ({ home: normalizeTeamName(m.home), away: normalizeTeamName(m.away) })) : undefined; }, [live]);
  const spursUpcoming = useMemo(() => live?.matches.filter(m => (m.status === "SCHEDULED" || m.status === "TIMED") && (m.home.includes("Tottenham") || m.away.includes("Tottenham"))).slice(0, 6) ?? [], [live]);
  const scenarioOverrides = useMemo<ScenarioOverride[]>(() => spursUpcoming.flatMap(m => { const result = scenario[`${m.home}-${m.away}`]; return result && result !== "AUTO" ? [{ home: normalizeTeamName(m.home), away: normalizeTeamName(m.away), result }] : []; }), [scenario, spursUpcoming]);
  const match = useMemo(() => prediction(home, away, liveResults, historical, players), [home, away, liveResults, historical, players]);
  const table = useMemo(() => simulation(liveResults, liveFixtures, scenarioOverrides, historical, players), [liveResults, liveFixtures, scenarioOverrides, historical, players]);
  const ratings = eloRatings(liveResults);
  const spursRow = table.find(row => row.team === "Tottenham") ?? { avg: 6, top4: 0.386, top6: 0.62 };
  const spursMatches = live?.matches.filter(m => m.home.includes("Tottenham") || m.away.includes("Tottenham")).slice(0, 5) ?? [];
  const refreshLive = async () => { setIsRefreshing(true); setLiveError(null); try { const response = await fetch("/api/live", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error); setLive(data); } catch (error) { setLiveError(error instanceof Error ? error.message : "Unable to refresh live data"); } finally { setIsRefreshing(false); } };
  useEffect(() => { void refreshLive(); fetch("/api/historical").then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setHistorical(data.teams); }).catch(() => setHistorical([])); fetch("/api/players").then(async response => { const data = await response.json(); if (!response.ok) throw new Error(data.error); setPlayers(data.players); }).catch(() => setPlayers([])); }, []);
  useEffect(() => { if (!players.length) return; setSelectedLineups(current => { const next = { ...current }; for (const team of teams) if (!next[team]) next[team] = players.filter(player => normalizeTeamName(player.team) === team).sort((a, b) => playerScore(b) - playerScore(a)).slice(0, 11).map(player => player.id); return next; }); }, [players]);
  const lineupFor = (team: string) => players.filter(player => normalizeTeamName(player.team) === team).sort((a, b) => playerScore(b) - playerScore(a));
  const selectedFor = (team: string) => lineupFor(team).filter(player => (selectedLineups[team] ?? []).includes(player.id));
  const lineupScore = (team: string) => { const selected = selectedFor(team); return selected.length ? Math.round(selected.reduce((total, player) => total + playerScore(player), 0) / selected.length) : 0; };
  const togglePlayer = (team: string, id: number) => setSelectedLineups(current => { const selected = current[team] ?? []; return { ...current, [team]: selected.includes(id) ? selected.filter(playerId => playerId !== id) : selected.length < 11 ? [...selected, id] : selected }; });

  return <main className="site-shell">
    <section className="hero-section"><header className="topbar"><div className="brand">SPURSCOPE</div><nav><a href="#predict">PREDICT</a><a href="#simulate">SIMULATE</a><a href="#scenario">SCENARIO</a></nav></header><div className="hero-rule" /><div className="hero-mark"><div className="mark-halo" /><img src="/spurs-logo.png" alt="Tottenham Hotspur cockerel" /></div><div className="hero-copy"><div className="kicker">Tottenham Hotspur / Premier League analytics</div><h1>Can Spurs<br />beat the odds?</h1><p>Predict matches. Simulate the season.<br />Explain what the numbers are really saying.</p></div><div className="hero-bottom"><span>SCROLL TO EXPLORE ↓</span><span>{live ? "LIVE DATA CONNECTED" : "LIVE DATA / CONNECTING"}</span></div></section>
    <section className="story-section" id="predict"><div className="section-label">01 — READ THE GAME</div><h2>The numbers<br />behind the noise</h2><p className="intro">SPURSCOPE turns live match data into a clear view of momentum, risk and possibility.</p><div className="metric-grid"><article><small>CURRENT ELO</small><strong>{Math.round(ratings.Tottenham ?? 1782)}</strong><span>Power rating</span><em>live rating</em></article><article className="gold-card"><small>TOP FOUR ODDS</small><strong>{pct(spursRow.top4)}</strong><span>Model probability</span><em>after live results</em></article><article><small>PROJECTED FINISH</small><strong>{Math.round(spursRow.avg)}th</strong><span>Expected position</span><em>range: 4th—9th</em></article></div><div className="scenario-intro" id="scenario"><div><div className="section-label">02 — TEST THE SEASON</div><h3>What if the next result<br />went the other way?</h3><p>Change a result and see the table move. The model stays transparent: every shift has a reason.</p></div><div className="next-match"><small>NEXT MATCH</small><strong>{spursUpcoming[0] ? `${normalizeTeamName(spursUpcoming[0].home)}  v  ${normalizeTeamName(spursUpcoming[0].away)}` : "Tottenham  v  Newcastle"}</strong><b>WIN &nbsp; DRAW &nbsp; LOSS</b><span>Projected finish: {Math.round(spursRow.avg)}th → {Math.max(1, Math.round(spursRow.avg) - 1)}th</span></div></div></section>
    <section className="dashboard-section" id="simulate"><div className="dashboard-head"><div><div className="section-label">03 — INTERACTIVE MODEL</div><h2>Make the season yours.</h2></div><div className="badge">{live ? "LIVE DATA CONNECTED" : "MVP • DEMO FALLBACK"}</div></div><div className="dashboard-grid"><section className="panel" id="predictor"><h4>Match predictor</h4><div className="controls"><label>HOME<select value={home} onChange={e => setHome(e.target.value)}>{teams.map(t => <option key={t}>{t}</option>)}</select></label><span className="versus">VS</span><label>AWAY<select value={away} onChange={e => setAway(e.target.value)}>{teams.filter(t => t !== home).map(t => <option key={t}>{t}</option>)}</select></label></div><div className="score"><strong>{match.homeRate.toFixed(2)} – {match.awayRate.toFixed(2)}</strong><span>expected goals</span></div><div className="probabilities"><div><small>HOME WIN</small><b>{pct(match.homeWin)}</b></div><div><small>DRAW</small><b>{pct(match.draw)}</b></div><div><small>AWAY WIN</small><b>{pct(match.awayWin)}</b></div></div></section><section className="panel"><h4>Elo power ratings</h4><table className="table"><thead><tr><th>Team</th><th>Elo</th><th>Strength</th></tr></thead><tbody>{Object.entries(ratings).sort(([, a], [, b]) => b - a).map(([team, elo]) => <tr key={team}><td className={team === "Tottenham" ? "highlight" : ""}>{team}</td><td>{Math.round(elo)}</td><td><div className="bar"><i style={{ width: `${Math.max(8, Math.min(100, (elo - 1400) / 2))}%` }} /></div></td></tr>)}</tbody></table></section><section className="panel wide"><h4>Where will Spurs finish? <span>5,000 season simulations</span></h4><table className="table"><thead><tr><th>Team</th><th>Expected finish</th><th>Top 4</th><th>Top 6</th></tr></thead><tbody>{table.slice(0, 8).map(row => <tr key={row.team}><td className={row.team === "Tottenham" ? "highlight" : ""}>{row.team}</td><td>{row.avg.toFixed(1)}</td><td>{pct(row.top4)}</td><td>{pct(row.top6)}</td></tr>)}</tbody></table><p className="notice">{liveFixtures ? "Using completed live results and the full scheduled fixture list." : "Using demo results until live data is connected."}</p></section><section className="panel wide"><h4>What-if scenario engine</h4>{spursUpcoming.length ? <div className="scenario-grid">{spursUpcoming.map(m => { const key = `${m.home}-${m.away}`; return <div className="scenario-row" key={key}><span>{normalizeTeamName(m.home)} v {normalizeTeamName(m.away)}</span><select value={scenario[key] ?? "AUTO"} onChange={e => setScenario(current => ({ ...current, [key]: e.target.value as "AUTO" | "WIN" | "DRAW" | "LOSS" }))}><option value="AUTO">Model prediction</option><option value="WIN">Spurs win</option><option value="DRAW">Draw</option><option value="LOSS">Spurs lose</option></select></div>; })}</div> : <p className="notice">Connect live data to configure upcoming Spurs scenarios.</p>}</section></div></section>
    <section className="live-section"><div className="section-label">04 — LIVE PREMIER LEAGUE</div><h2>What is happening now.</h2>{liveError ? <p className="notice">Live feed unavailable: {liveError}</p> : live ? <div className="live-grid"><div className="live-table"><h4>Table</h4><table className="table"><thead><tr><th>Pos</th><th>Team</th><th>P</th><th>Pts</th><th>GD</th></tr></thead><tbody>{live.standings.slice(0, 8).map(row => <tr key={row.team}><td>{row.position}</td><td className={row.team.includes("Tottenham") ? "highlight" : ""}>{row.team}</td><td>{row.played}</td><td>{row.points}</td><td>{row.goalDifference}</td></tr>)}</tbody></table></div><div className="live-table"><h4>Spurs fixtures</h4><table className="table"><tbody>{spursMatches.map(m => <tr key={m.id}><td>{new Date(m.date).toLocaleDateString()}</td><td>{m.home} v {m.away}</td><td>{m.homeGoals === null ? m.status : `${m.homeGoals} – ${m.awayGoals}`}</td></tr>)}</tbody></table><p className="notice">Updated {new Date(live.updatedAt).toLocaleTimeString()}</p></div></div> : <p className="notice">Connecting to live Premier League data…</p>}</section>
    <section className="lineup-section"><div className="section-label">05 — LINEUP BUILDER</div><h2>Who wins the XI?</h2><p className="intro">Build both lineups and compare current form, availability and squad quality before the whistle.</p><div className="lineup-teams"><div className="lineup-team"><label>HOME TEAM<select value={home} onChange={e => setHome(e.target.value)}>{teams.map(team => <option key={team}>{team}</option>)}</select></label><div className="lineup-score"><strong>{lineupScore(home)}</strong><span>/ 100 lineup score</span></div><div className="player-list">{lineupFor(home).slice(0, 18).map(player => <button className={(selectedLineups[home] ?? []).includes(player.id) ? "player selected" : "player"} key={player.id} onClick={() => togglePlayer(home, player.id)}><span>{player.name}<small>{player.position ?? "Player"}</small></span><b>{playerScore(player)}</b></button>)}</div></div><div className="lineup-vs">VS<div>{lineupScore(home) && lineupScore(away) ? (lineupScore(home) > lineupScore(away) ? `${home} edge` : lineupScore(home) < lineupScore(away) ? `${away} edge` : "Evenly matched") : "Select players"}</div></div><div className="lineup-team"><label>AWAY TEAM<select value={away} onChange={e => setAway(e.target.value)}>{teams.filter(team => team !== home).map(team => <option key={team}>{team}</option>)}</select></label><div className="lineup-score"><strong>{lineupScore(away)}</strong><span>/ 100 lineup score</span></div><div className="player-list">{lineupFor(away).slice(0, 18).map(player => <button className={(selectedLineups[away] ?? []).includes(player.id) ? "player selected" : "player"} key={player.id} onClick={() => togglePlayer(away, player.id)}><span>{player.name}<small>{player.position ?? "Player"}</small></span><b>{playerScore(player)}</b></button>)}</div></div></div></section><div className="refresh-row"><button className="refresh-button" onClick={() => void refreshLive()} disabled={isRefreshing}>{isRefreshing ? "REFRESHING LIVE DATA…" : "REFRESH LIVE DATA ↻"}</button></div><footer><span>SPURSCOPE</span><p>Predict&nbsp; • &nbsp;Simulate&nbsp; • &nbsp;Explain</p><small>LIVE DATA / FOOTBALL-DATA.ORG</small></footer>
  </main>;
}
